### ISSUE TITLE
HD audio Passthrough disabled on Shield not updated to Marshmallow

### ISSUE THREAD

**Issue by rhinoTV** [koying/SPMC#87] opened 2016-03-15 20:18 UTC
No HD audio passthrough on Shield with Lollipop.

**Comment by koying** [comment] 2016-03-16 11:24
Note to self: 
Re-enable RAW passthrough on Shield 2.1.
Way-to-go: Pseudo-passthrough devices for PCM/RAW/IEC

**Comment by koying** [comment] 2016-03-16 11:25
Ah, sorry, is a duplicate of #83

**Closed as completed by koying** 2016-03-16 11:25 UTC
Labels: duplicate
