### ISSUE TITLE
SPMC 16.2 Local subtitles not loading

### ISSUE THREAD

**Issue by Promhtheas** [koying/SPMC#205] opened 2016-04-10 06:58 UTC
Im using SPMC 16.2 on an RK3229 device that streams video files over an SMB network.While the subtitle files are named exactly as the video files and reside next to them in the same folder,the subtitles are not loading.Download of subs through subtitle service works fine.

Any clues?

Thanks in advance!

**Comment by vultux** [comment] 2016-04-11 23:06
Im having the same problem on Nvidia Shield and I would like to add that when I open the subtitle manually the SMPC freezes.

EDIT: I tried the new version 16.2.1 and still have the same problem.

**Comment by babaloui** [comment] 2016-04-14 10:05
I am running SPMC 16.2 on Nvidia Shield as well. Files over SMB with subs in same folder. No problems what so ever for me.

**Comment by Cherry-Dude** [comment] 2016-04-18 20:57
Hi there, just to get it out of the way - fantastic software!
I have had no problems with subtitles. Until today, as I am experiencing the exact same problem as vultux - SPMC does not find the subtitle automatically, if I select manually the "unknown external 1/1" is displayed but no subtitles still do not work, or it just freezes.
Only thing I have done between working and broken subtitles is fooling around with audio settings.
Using brand new 16GB SHIELD with SHIELD Android TV SW Version 3.1. Subtitles over SMB and named as video files.

Edit, aw sorry, I'm using SPMC 16.2.1 - still no lovely subtitles for me

**Comment by koying** [comment] 2016-04-21 16:11
Works for me, too.
Would need a debug log to tell more...

**Comment by vultux** [comment] 2016-04-22 00:54
Follow attached my LOG file.

I think the problem is with foreign subtiltles because I tried with Star Wars and english subtitles and worked fine. I'm from Brazil and we use some accented characters, sorry I don't now if this is the correct word.

I'm attaching a portuguese brazilian subtitle for your tests too.
[SPMC_Log-Brazilian_subtitle-042116.zip](https://github.com/koying/SPMC/files/230947/SPMC_Log-Brazilian_subtitle-042116.zip)

Thank you!

**Comment by koying** [comment] 2016-04-22 17:20
Mmm... Still working for me: http://imgur.com/zBBtOIy

**Comment by Cherry-Dude** [comment] 2016-04-22 18:34
Hello again.
After restoring all audio and video settings to default, my subtitles started working again. After I tested it out for some time I set up audio again (Andrid RAW passthrough: all but Dolby Digital (AC3) transcoding, all other settings as default) - still worked. Then I went and set up video (no biggies here, just auto play next video and Adjust Display Refresh Rate set to always) - and lo and behold subtitles still works!
There might have been some obscure setting somewhere that I had activated when the didn't work, but I have not really been able to reproduce the problem.

Anyway, try the restore to default, maybe it could help you other guys too.

**Comment by oranheim** [comment] 2016-05-01 10:19
I'm unable to download subtitles using (Ponapisi, OpenSubtitles, Subscene). I get an error "unable to download .. from ..".

Here is my log: https://gist.github.com/oranheim/713a483930c3299d6422edf272a48a90

**Comment by Cherry-Dude** [comment] 2016-05-02 18:10
Do any of you who experience problems by any chance have auto frame rate switch on the "always" setting?

**Comment by vultux** [comment] 2016-05-02 21:25
Yes.

I turned off the auto frame rate to test, SPMC load automatically only english subtitle, when I forced to load from folder the portuguese subtitle SPMC freeze again.

**Comment by jaracimrman** [comment] 2016-05-29 19:17
I had this bug too after enabling "auto-play" (after ending episode play another). When i finally found it after fiddling with every setting and disabling it, the subtitles showed up again.

**Comment by vultux** [comment] 2016-05-29 21:32
THANK YOU!!!!!!!!

Disabling the auto-play solved the problem for me too.

Thanks!

**Comment by notsureawake** [comment] 2016-06-25 01:02
Just wanted to post on this issue as well.  Using spmc 16.3.0 and subs won't load automatically.  Loading them manually causes spmc to freeze.  Going to Settings > Video > Playback and disabling "Play next video automatically" allows subs to be loaded automatically and work properly.

**Comment by Cherry-Dude** [comment] 2016-07-30 13:18
I have forgotten to mention the disabling of "Play next video automatically" also resolved all occurrences of this issue for me. It is very low priority, but could this be fixed in any way? Otherwise I'll have to settle for manually selecting the next videos, but on the other hand that might help me getting more off the couch.

**Comment by vultux** [comment] 2016-08-01 22:18
I did a test with version 16.4.1 and the problem continues, when I reenabled the "Play next video automatically", external subtitles not loaded and when I forced load, going in "Find Subtitle" and loaded the correct subtitle the app freeze.

I'm using on ShieldTV.

**Comment by erratos** [comment] 2016-08-27 23:19
I have noticed that when I open contextual menu > audio settings > search for subtitles, the starting path switch with the autoplay status:
autoplay off,  path begin with NFS://
autoplay on,  path begin with VIDEODB:// (no subtitle there) 

I hope it will help to fix this issue

**Comment by koying** [comment] 2016-08-31 14:34
16.4.2 should have solve the issue

**Comment by mustang651** [comment] 2016-09-03 13:42
But it didn't for me :( Just checked on Nvidia Shield TV

**Comment by Cherry-Dude** [comment] 2016-09-03 13:45
Just tested it - same as mustang 651 no go for me. Still works flawlessly with "Play next video automatically" disabled though.

**Comment by koying** [comment] 2016-09-03 14:25
Ok, noted

**Comment by koying** [comment] 2016-09-03 14:55
Oups, indeed, was not in 16.4.2.
Is in the 16.5 beta, though: https://github.com/koying/SPMC/issues/435

**Closed as completed** 2016-11-30 16:46 UTC
Labels: bug
