### ISSUE TITLE
Blackscreen

### ISSUE THREAD

**Issue by pjg-pigeon** [koying/SPMC#97] opened 2016-03-17 13:19 UTC
Installed 16.1.1 to mx2 Android box, I see the first time run screen and the progress bar then it goes blank. 

Any suggestions? Also I am willing to assist you if you need me to do anything, like submitting logs or stuff

**Comment by koying** [comment] 2016-03-17 13:54
Probable duplicate of #84 
Do you confirm you your box is Android 4.3?

**Comment by pjg-pigeon** [comment] 2016-03-17 14:12
Thanks for the prompt reply.

No it's 4.2.2, is that the problem?
I sideloaded it, without checking if there were limitations.

**Comment by koying** [comment] 2016-03-17 14:34
Probably. I've received lots of feedback that < 4.4 gets black screen.
I'll close this one ank keep the other.

**Closed as completed by koying** 2016-03-17 14:34 UTC
Labels: duplicate

**Comment by koying** [comment] 2016-03-17 18:16
Please test http://download.semperpax.com/spmc/android-arm/SPMC-20160317-29f5ca3-fix_document_api17-armeabi-v7a.apk
