### ISSUE TITLE
SPMC problem with speak command  in Nvidia Shield V.6.0 firmware with new Google App

### ISSUE THREAD

**Issue by Shieldus** [koying/SPMC#1059] opened 2017-09-29 09:12 UTC
Hi,
after Nvidia Shield Update V 6.0 firmware with the new Google App 
The SPMC Speak Command in the search funktion doesn`t work anymore.
I hope you can help to fix this in a new SPMC Version.
Because this funktion is great and i don´t want to miss this.
This is why i used SPMC because kodi doesn`t have it.
SPMC is great !
Thanks for all!

Regards
Shieldus

**Comment by koying** [comment] 2017-09-29 13:48
Duplicate of #1058

**Closed as completed by koying** 2017-09-29 13:48 UTC
