### ISSUE TITLE
Stream info not showing

### ISSUE THREAD

**Issue by Firetv344** [koying/SPMC#213] opened 2016-04-14 18:04 UTC
i imported my movies from my server and its not pulling the stream info....its not showing aspect ratio, resolution, audio channels or if the movies are HD.....this was working in 16.1.2, i did a fresh install and still no luck......any suggestions...

**Comment by heymoe** [comment] 2016-04-14 18:09
SPMC v16.2.1 has just been released and might fix this problem. 

Changelog and link to the new APK can be found here:

http://spmc.semperpax.com/

Play Store version might not be updated yet.

**Comment by Firetv344** [comment] 2016-04-14 18:11
thats the version i did the fresh install with but still no luck 16.2.1

**Comment by uhnonuhmuhs** [comment] 2016-04-17 20:19
Posted what seems like the same issue here:

https://github.com/koying/SPMC/issues/207

I think 16.2.1 was intended to fix this issue but, unfortunately, has not. Hoping this gets resolved in the next release.

**Comment by koying** [comment] 2016-04-24 14:01
Fixed

**Closed as completed by koying** 2016-04-24 14:01 UTC
Labels: bug
