### ISSUE TITLE
Shield TV 3.2 Autoframerate only use RGB

### ISSUE THREAD

**Issue by FreshGodFather** [koying/SPMC#349] opened 2016-06-29 17:06 UTC
Hello,
today the new 3.2 Software was released.
Now its possible to activate ycbcr instead rgb.
Wenn ycbcr in the android system is activated and spmc has to change this to an another frequecy depends on a movie: the new framerate will be activated but colorspace is set to RGB.
Maybe the API changed and the old one which is currently in spmc only knows RGB

**Comment by devabuse** [comment] 2016-06-29 17:40
Can confirm.

ycbcr is selected and auto frame rate switch to 24p it defaults to rgb. It's always something with the shield tv.

Edit: tested with latest kodi krypton nightly, same issue

**Comment by FreshGodFather** [comment] 2016-06-29 19:22
when manualy change frequency in android-system settings there is no problem. So thats the proof ycbcr supports the different frequencies

**Comment by gumbi2400** [comment] 2016-06-30 07:13
Can confirm this issue. Seems it's any frame rate switch within SPMC. I might test out the latest Kodi to see if it's the same, though I suspect it is.

**Comment by koying** [comment] 2016-06-30 07:49
Did you try http://forum.kodi.tv/showthread.php?tid=228158&pid=2366834#pid2366834 ?
Haven't installd the update, yet...

**Comment by gumbi2400** [comment] 2016-06-30 08:20
Still no luck, though a touch better. It changes to YCbCr but a video drops back to RGB, while stopping the video returns to YCbCr where it was originally staying at RGB. Here's general steps including the hard reset:

1: Set to YCbCr 4:4:4 in settings.
   keep an eye on logcat here returns : 
`06-30 09:15:01.248   249   249 D hwcomposer: int nvhwc_display::set_sf_config(int): changing to actual mode 0: 1920x1080 60.000000 Hz
06-30 09:15:01.248   249   249 W hwcomposer: New DC mode 1920 x 1080 @ 60.00 Hz (YUV444/8/Rec.709/cea/limited)`

2: Open SPMC and play a 24p video

`06-30 09:18:40.388   249   249 D hwcomposer: int nvhwc_display::set_sf_config(int): changing to actual mode 30: 1920x1080 24.000000 Hz
06-30 09:18:40.388   249   249 W hwcomposer: New DC mode 1920 x 1080 @ 24.00 Hz (RGB/8/Rec.709/cea/limited)
06-30 09:18:40.388   249   249 D hwcomposer: display type 1: vblank period = 41666666 ns`

3: Stop video

`06-30 09:20:02.713   249   249 D hwcomposer: int nvhwc_display::set_sf_config(int): changing to actual mode 0: 1920x1080 60.000000 Hz
06-30 09:20:02.713   249   249 W hwcomposer: New DC mode 1920 x 1080 @ 60.00 Hz (YUV444/8/Rec.709/cea/limited)
06-30 09:20:02.713   249   249 D hwcomposer: display type 1: vblank period = 16666667 ns` 

Hope this gives a bit more insight. Let me know if additional info is needed.

**Comment by koying** [comment] 2016-06-30 08:29
If I got it right, YUV444 is only available at 50/59.94/60 Hz (http://forum.kodi.tv/showthread.php?tid=220297&pid=2366826#pid2366826).

Maybe try a 50 fps vid to confirm.

Quite confusing though ;)

**Comment by gumbi2400** [comment] 2016-06-30 09:22
That appears to be no longer the case as I am definitely getting 1080p 60hz as well as 23.976 YUV444 according to logcat. 

I think this may not be a bug in SPMC directly, I gave it a shot in PLEX as well and saw that it's dropping to RGB during playback, and reverting back to YUV444 when stopping.

**Comment by showmak** [comment] 2016-06-30 09:28
@gumbi2400 

How do you get the this info...

`06-30 09:18:40.388 249 249 D hwcomposer: int nvhwc_display::set_sf_config(int): changing to actual mode 30: 1920x1080 24.000000 Hz 06-30 09:18:40.388 249 249 W hwcomposer: New DC mode 1920 x 1080 @ 24.00 Hz (RGB/8/Rec.709/cea/limited) 06-30 09:18:40.388 249 249 D hwcomposer: display type 1: vblank period = 41666666 ns`

**Comment by gumbi2400** [comment] 2016-06-30 10:13
It's straight forward enough, just use logcat in ADB.

**Comment by showmak** [comment] 2016-06-30 10:37
I think this is beyond me, I am just a newbie in these things.

**Comment by 99rook99** [comment] 2016-06-30 13:01
YCrCb 4:4:4 is only available for 4k 23.976 according to HDMI 2.0a specs, when watching 4k

**Comment by FreshGodFather** [comment] 2016-06-30 13:10
"If I got it right, YUV444 is only available at 50/59.94/60 H"
Can be, but on 1080p YCrCbr (maybe its 4:2:0 or something) is selectable in the system menu with 24p.

**Comment by showmak** [comment] 2016-06-30 13:34
Ok. HDMI resolution set to 1080p 60Hz, I selected YCrCbr 4:4:4 from HDMI color space, shield connected to my AVR through HDMI 1.4, played a 1080p 23.976 movie, SPMC automatically changed the refresh rate, but the movie was played in YUV420p. Changed the color space to RGB, and same thing movie played in YUV420p. What does that mean?

**Comment by gumbi2400** [comment] 2016-06-30 14:03
@showmak Can you provide the logcat logs for the HDMI portion after you start playing? I'm curious to see what android is setting it to. 

How are you determining the color space when playing the video? It should be encoded in YUV420 (video standard) but may still be output from the shield as RGB.

**Comment by showmak** [comment] 2016-06-30 15:16
@gumbi2400 
I want to try to get the logcat but I don't know how. Any step by step instructions?

**Comment by devabuse** [comment] 2016-06-30 17:38
@koying 
I tried the suggestion on the forum. Disconnecting the power and seeing if it would stick after that, but no dice.

@gumbi2400 
I have attached a log file. The steps i took are:

1) Start the logcat
2) Press play on the video, a nice episode of Sopranos.
3) Press stop
4) Stop logcat

In the log I have done some searching: ycbcr is mentioned as the color space set on nvidia. Searching on rgb shows, what i believe spmc setting the colorspace to after the frame rate switch. 

[android.log.zip](https://github.com/koying/SPMC/files/342017/android.log.zip)

If you need me to provide more logs and test other scenario's, let me know.

**Comment by FreshGodFather** [comment] 2016-06-30 18:16
i can confirm this:

Chosen manualy 23,976 in android system menu
06-30 19:47:09.181   231  1312 D hwcomposer: Chosen hdmi mode: 1920 x 1080 @ 23.98 Hz (YUV444/8/Rec.709/cea)

Chosen manualy 60 in android system menu
06-30 20:00:12.828   231   231 W hwcomposer: New DC mode 1920 x 1080 @ 60.00 Hz (YUV444/8/Rec.709/cea/limited)

Start playing 23,976 file in SPMC with autoframerate-switch
06-30 20:05:12.530   231   231 W hwcomposer: New DC mode 1920 x 1080 @ 23.98 Hz (RGB/8/Rec.709/cea/limited)

stoppend playing file
06-30 20:05:26.326   231   231 W hwcomposer: New DC mode 1920 x 1080 @ 60.00 Hz (YUV444/8/Rec.709/cea/limited)

**Comment by koying** [comment] 2016-06-30 18:43
That _might_ be a FW issue (waiting for confirmation).
Will test this WE, anyway.

**Comment by heymoe** [comment] 2016-06-30 18:52
I want to say I saw a post on the Nvidia forums where someone said to either disable hardware acceleration maybe just Surface or both or some other combo and said that things stayed YUV444 on refresh rate changes. I can't seem to find that post again but I'm still looking but maybe something to try / test.

**Comment by devabuse** [comment] 2016-06-30 20:13
I have tried all manner of combinations of that, but none of them work. I have also send a support request to nvidia about this, but really, if this turns out to be another firmware issue that takes 6 months to resolve ... I am dumping this thing and going back to a mede8er. At least it plays 1080p with proper picture quality and refresh rates

**Comment by heymoe** [comment] 2016-06-30 20:20
hmmm.. What if you manually set 23.976 YUV444 via the system menu, go into SPMC and start playing something that is 23.976. Assuming SPMC doesn't have to change frame-rates since it's already at 23.976 (Maybe disable auto frame-rate while testing this), does it stay and play at YUV4444?

**Comment by FreshGodFather** [comment] 2016-06-30 20:36
If autoframerate is disabled it stay at 23.976 yuv. If enabled it switch to 23.976 rgb

**Comment by wesk05** [comment] 2016-07-01 02:16
@koying : in the Kodi forum post, I was referring to HDR output. HDR is available only in 4K 50/59.94/60Hz. In case you haven't seen my post about HDR, HDR does work in SPMC and Kodi.

~~As for this colorspace issue, in this 3.2 firmware something has changed; either the mode name or the API itself. It is actually switching to 24.000Hz and not 23.976Hz. I haven't figured out a way to set 24.000Hz mode to YCbCr 4:4:4. I can do it in TVHz, but then refresh rate switching breaks completely.~~

Switching to 24.000 may have been a one-off thing. It does indeed switch to 23.976 mode. Upon checking the issue further it looks like YCbCr setting is not really tied to the resolution/refresh rate nor is a global setting. nVIDIA may have to correct this issue.

**Comment by wesk05** [comment] 2016-07-01 02:24
@heymoe : Even if you set it to YCbCr 4:4:4 23.976Hz, it will switch to RGB. The only solution now is to set it manually to YCbCr 4:4:4 and disable refresh rate switching.

**Comment by devabuse** [comment] 2016-07-01 04:43
@wesk05 
Can this be fixed on the Kodi/SPMC end? Or is this an issue with the shield itself? 

In the hdmi settings on the shield it lists the various 4k options with refresh rates(60/50/23.976), but only shows 1080/60 for 1080. SPMC can auto switch it to 1080/24, but you can't set this manually.

**Comment by wesk05** [comment] 2016-07-01 06:28
@mikecoenen 
I don't know whether this is a SPMC, Kodi issue or Shield firmware issue. 

When connected to a 4K display, you will only see 1080p60 in Shield's settings. I don't think SPMC will auto switch from 4K xxx to 1080p24.If you want your TV to do the scaling, you have to set Shield output to 1080p60. It will then switch to 1080p24 when playing 23.976/24.000fps content.

**Comment by devabuse** [comment] 2016-07-01 07:54
It can't switch from 4k to 1080p, i believe this is an android limitation. Since you can't manually set it to 1080/24p on a 4k display. We are stuck with two subpar solutions.

1) Set it to 4k24 manually and disable adjust display rate for ycrcb output to work. This means the shield will upscale, which in most cases(when playing 1080 content) results in a blurry mess compared to what a good television can do.
2) Set it to 1080/60 and enable adjust display rate to allow for 1080/24p but with rgb and non-optimal picture quality. At least i have not had much succes in reducing banding on certain tests.

 I am currently in the process of testing various other options like disabling mediacodec, (hard) reboots with different options set. If i find another workaround i will share it.

Edit: After 2 hours of trying various options, was unable to find a workaround other than disabling auto refresh rate.

**Comment by wesk05** [comment] 2016-07-01 17:17
@mikecoenen 

> 1) Set it to 4k24 manually and disable adjust display rate for ycrcb output to work. This means the shield will upscale, which in most cases(when playing 1080 content) results in a blurry mess compared to what a good television can do.

I may have to disagree with this statement. Shield's upscaling is certainly not as good as on a TV, but you certainly won't get a blurry mess :)

**Comment by classicjazz** [comment] 2016-07-02 11:38
If the picture is "blurry", then it's likely that you don't have the right settings for the HQ scalers. Please try the settings for 4K in the Wiki. 
https://github.com/koying/SPMC/wiki/Recommended-video-settings-for-SPMC%2C-NVIDIA-Shield-TV-and-UHD-%284K%29-TVs-with-4K-GUI

Yes, it would be nice to have a better scaler than Lanczos3 - optimised. But I haven't gotten Nvidia to respond about potential use of Maxwell-specific MFAA scaler and deinterlacer APIs. And I haven't found any non-MadVR scaler work in Kodi comparable to MPV's ewa_lanczossharp scaler that could be implemented on the Shield.

**Comment by devabuse** [comment] 2016-07-02 12:02
I actually do have those set up correctly. Just not really a fan of them. I bought a a television set which has an amazing upscaler and prefer to use that for 1080p upscaling. Unfortunately even with lanczos, it simply does not compare. A blurry mess is a bit of an overstatement though.

In any case i continued my search for a workaround that would allow users to operate the shield at 1080 on a4k set while keeping the ycbcr stuff. It only works when you disable auto refresh rate but this introduces a lot of judder in my case, requiring the use of motion interpolation on the tv, which brings the dreaded soap opera effect, but it's an option i guess.

I hope koying can do something about it though. I have also tested plex, it suffers from the same issues. So many apps having issues with this, must be some kind of api change on the shield.

**Comment by salondigital** [comment] 2016-07-02 12:40
I post here the same than nvidia shield official forums:

Finally I had more free time to testing. And yes, the problem is only in the fuck%&ing "23.76" Hz. So for testing purpose, I modified the original Spear's test to different refresh rates. 23.976 (original), 25p, 25i, 30p, 30i, 50p, 50i, 60p and 60i. With ALL of this and SPMC with automatic refresh rate change, the test plays PERFECTLY, with zero banding and all square (YCbCr and RGB) checked EXCEPT the original 23.976.

Here are the tests in a zip file (delete the spaces between letters): h t t p s : / / m e g a . n z /#!wcY0BZ4C!_GNIp7v8iPl0OhHY3szdWnDl97e6hDhWXKrd37289xY

Then, I installed tvhz and change manually to the two 24 Hz resolution, in both if you go to HDMI Settings option, you can see that the space colour is "RGB Limited" and one of them is "23.976 Hz" and the another the Shield shows "24 Hz".

So my conlusion is Nvidia added a new 23.976 Hz, but the apps changes to the old ones (24 and the another 23.976), in these modes you can't change the colour space (I tried, but after select YCbCr, Shield changes to 60 Hz). And If you check the changelog (sorry is in spanish language):

"Improved picture quality with 23.976 refresh rate mode"

Bingo ;)

I used: Panasonic GT30 1080p, Shield TV 3.2 16GB with YCbCr in all refresh rates and SPMC with auto-refresh rate ON, mediacodec (surface) ON and mediacodec Off.

Now the question is...is an app problem (Plex, SPMC, etc.) that uses the old 23.976 Hz and need to be updated or is an Nvidia shield bug?

And yes...[b]deinterlace (HW) is completly BROKEN[/b], 1080i 25 (50) fps interlaced H.264. Finally banding is gone and now I can't watch live tv :S

**Comment by KOKOtm** [comment] 2016-07-09 11:19
Also tried it for myself (Reboot device after every resolution switch) 

4K@23.976 Y444: 
24p Content = Y444 (no hz-switch)
50p Content = Y420 (hz-switch)

4k60 Y420:
24p: RGB Limited (hz switch)
50p: Y420 (hz switch)

1080p60 Y444:
24p: RGB Limited (hz switch)
50p: RGB Limited (hz switch)

My goal would be 1080p60 with Yxxx, regardless of the content. The TV still upscales a lot better than lanczos3 optimised, looks too soft. Perhaps some updates will fix that.

My dream would be auto-resolution-switch, auto-hz-switch, YCBCR420 in every content... if someone knows a device that can do that with DTS-HD/DolbyHD bitstreaming please comment ;-)

**Comment by devabuse** [comment] 2016-07-16 08:05
What is the consensus on this? Shield issue or fixable in SPMC?

**Comment by DaMacFunkin** [comment] 2016-07-16 13:26
I would say shield issue, in 3.1 you could watch Netflix in 4K24hz or watch 10bit files in 24hz, in 3.2 you can not.

**Comment by FreshGodFather** [comment] 2016-07-25 10:26
Any news?

**Comment by koying** [comment] 2016-07-25 10:32
It's a FW bug, nothing SPMC can do about it.

**Closed as completed by koying** 2016-07-25 10:32 UTC
Labels: To be tested

**Comment by FreshGodFather** [comment] 2016-07-25 15:44
ok, thanks for the quick reply :-)
