### ISSUE TITLE
Not able to launch SPMC on Fire TV

### ISSUE THREAD

**Issue by mjbxx** [koying/SPMC#80] opened 2016-03-14 21:00 UTC
Not able to fully launch SPMC on a Fire TV as posted (http://forum.kodi.tv/showthread.php?tid=264126) in the Kodi/Android forum, I do not understand why I can not get SPMC running.

**Comment by koying** [comment] 2016-03-15 15:29
Unfortunately, I do not have a FireOS3 device anymore.
Please provide an "adb logcat" of when SPMC is starting

**Comment by mjbxx** [comment] 2016-03-15 18:10
I honestly have no idea how to provide a adb logcat from the Fire TV. I mentioned in the thread that SPMC 15.0 Launcher works. Is there anyway to compare that launcher APK with the non launcher APK? In the mean time I can try to figure out how to provide the logcat. Worst case scenario is that I wait for TWRP and a pre-rooted OS 5 rom from @rbox over at XDA.

**Comment by koying** [comment] 2016-03-16 11:33
Possible duplicate of #84

**Comment by guidosarducci** [comment] 2016-03-17 06:12
Having the same hang on blank screen on a FireTV, V1, Fire OS 3, rooted.  Attached a logcat below, and let me know if anything else will help. No issues with previous versions (Kodi or SPMC).

[spmc-logcat.txt](https://github.com/koying/SPMC/files/177328/spmc-logcat.txt)

**Comment by koying** [comment] 2016-03-17 14:33
@guidosarducci Thanks for the logcat. That makes the issue obvious :)
I'll close this one in favor of #84

**Closed as completed** 2016-03-17 14:34 UTC
Labels: duplicate

**Comment by koying** [comment] 2016-03-17 18:17
Please test http://download.semperpax.com/spmc/android-arm/SPMC-20160317-29f5ca3-fix_document_api17-armeabi-v7a.apk

**Comment by guidosarducci** [comment] 2016-03-17 20:05
Tested and starts up properly now.  Thanks for the Fire TV (and 4.x) love!
