### ISSUE TITLE
no sound through tv issue

### ISSUE THREAD

**Issue by alphabetagaga** [koying/SPMC#141] opened 2016-03-24 16:35 UTC
SPMC 16.1.2 running on Shield TV
AVR: Yamaha RX-V673 connected with hdmi to Sony KDL 32s2010
Channels: 5.1 set (5.1 plugged into AVR)

good afternoon

i have a issue getting sound through the connected tv. navigate to settings>system >audio output and

if i select 'enable passthrough' and disable all 3 of DD, DD+ and DTS (only those 3 apply to my amp), i'll get audio through the tv when the amp is off. when switching the amp on, i'll get PCM show on the amp display.

if i select 'enable passthrough' and enable all 3 of DD, DD+ and DTS, i'll get no sound though the tv when the amp is off. when switching the amp on, i'll get DD, DD+ or DTS show on the amp display.

if i disable 'enable passthough' completely, i'll get audio through the tv when the amp is off. when switching the amp on, i'll get PCM show on the amp display.

any suggestions as how to get sound though the tv when the amp is off, whilst maintaining a DD, DD+ or DTS track when the amp is on?

i hope the above explains my issue. i have a log here http://xbmclogs.com/pgpoby9ph

**Comment by Wordstar1981** [comment] 2016-03-25 12:16
Have you tried the new iec passthrough option? 
Thats the one that does the trick for me with my yamaha amp and lg tv. 
See this thread here: https://github.com/koying/SPMC/issues/76 Koying implemented it because of my problem

**Comment by alphabetagaga** [comment] 2016-03-25 14:54
thanks for replying. using the same movie file as before (which only has a dts track), i adjusted the settings as follows

audio output device '**android, iec passthrough**'
passthrough output device '**android, raw passthrough**'

and enable passthough with dd, dd+ and dts checked, i get no sound from the tv still. i get a dts track from the amp

if i adjust as follows

audio output device '**android, iec passthrough**'
passthrough output device '**android, iec passthough**'

and enable passthough with dd, dd+ and dts checked, i get white noise from the tv and i also get a white noise from the amp

**Comment by Wordstar1981** [comment] 2016-03-25 15:47
hmmm strange... when i set the following i get perfect sound from amp and tv:

audio output device 'android, iec passthrough'
passthrough output device 'android, iec passthough'

Seems your tv does not support dts sound?

**Comment by alphabetagaga** [comment] 2016-03-25 16:09
unfortunately, it is the same outcome if i play a non dts track though eg a 1.0 mono track (laurel and hardy short). again no sound from the tv.

**Comment by Wordstar1981** [comment] 2016-03-25 16:27
Then i guess your tv only likes pcm?

**Comment by koying** [comment] 2016-03-25 17:01
As a matter of fact, this TV only decodes AC3: https://docs.sony.com/release/specs/KDL32S2010_mksp.pdf

**Comment by alphabetagaga** [comment] 2016-03-25 17:26
ah ok thanks very much koying. so is there anything in the spmc setting i need to adjust? or do i simply go with option 1 in my original post and stick with being able to get sound through the tv and a pcm track though the amp?

**Comment by frankiecam** [comment] 2016-04-01 06:51
i have the same problem i think using android box i set audio to passthrough in spmc tick dts dd enable transcoding my hdmi goes to my yamaha avreciever set to amp  and if play a movie with 5.1 sound all i get is noise  
the only way to get soundtrack is disable passthrough then its just pcm 2.1

**Comment by koying** [comment] 2016-04-01 07:49
Please try http://download.semperpax.com/spmc/android-arm/SPMC-20160330-59124a3-spmc-jarvis-armeabi-v7a.apk to see if it solves the issue (in IEC mode)

**Comment by frankiecam** [comment] 2016-04-01 08:24
will do thank you

**Comment by frankiecam** [comment] 2016-04-01 11:18
yep that fixed it great work
       thank you

**Comment by koying** [comment] 2016-04-01 11:28
duplicate of #162

**Comment by alphabetagaga** [comment] 2016-04-01 16:35
regarding the download link above - does it apply to my issue in the op?

**Closed as completed** 2016-04-03 12:33 UTC
Labels: bug, duplicate

**Comment by WebBuddha** [comment] 2017-05-09 18:04
I got the same problem with AC3 sound in my moviefiles.
The Settings did it for me and my Teufel Cinebar 52.
audio output device 'android, iec passthrough'
passthrough output device 'android, iec passthough'
