### ISSUE TITLE
Question: Voice search in video addons

### ISSUE THREAD

**Issue by msammut** [koying/SPMC#137] opened 2016-03-23 10:42 UTC
So as far as I am aware you have voice search and recommendations working for local content in SPMC - awesome by the way! - but what I found would be even more awesome is a way to search within video addons using voice.... I can't seem to find a way to do this with the nvidia shield remote or controller. (I know it can be done with 3rd party apps on your phone as a remote, but I would like to use the stock controllers)

Is this at all possible? i.e. when in the search box in SPMC click the voice command button on the remote and the recognized text gets entered in the SPMC search box itself..... OR in the voice search results bring up results from within a video addon such as Exodus?

If not - please consider this a feature request :)

**Comment by ruppert10** [comment] 2016-03-23 11:06
+1

**Comment by ErAzOr2k** [comment] 2016-03-23 11:23
lol we posted this feature request nearly the same time :)

**Comment by ghost** [comment] 2016-03-23 11:42
I cant see that happening. There are so many devices that use voice search and so many that dont and those that do will be implemented in different ways. Its one thing using nvidias voice search and getting the system to return SPMC as a result. Getting SPMC to understand what is being said by voice and convert it to text is a different story. I really cant see it happening.

**Comment by ErAzOr2k** [comment] 2016-03-23 12:05
@tdbegley28 Google is providing an API for that

**Comment by koying** [comment] 2016-03-23 12:06
Voice search is an Android feature, really. I _think_ the way it's done currently in SPMC is restricted to Android TV, though.

Voice recognition is something else. It _should_ be possible to add it to any SPMC/Kodi input, like global search, as there is indeed an API for that

**Comment by koying** [comment] 2016-03-23 12:09
Is there a way to do a search into an addon?
I.E. if doing a plain search into Kodi/SPMC, are addons results returned?

If not, there is no way to do it via Android, either, obviously...

**Comment by ErAzOr2k** [comment] 2016-03-23 12:14
I just can tell you that some Addons provides an search feature where the keyboard opens and I can type for the search term

**Comment by msammut** [comment] 2016-03-23 12:17
Yeah, but thinking about it addons change all the time, so coding in voice search support for a specific addon might be short lived.
I guess the sustainable option is to just allow a voice recognition option in the native search within SPMC (when the on screen keyboard comes up)

**Comment by ErAzOr2k** [comment] 2016-03-23 12:22
I also think an additional button for voice recognizing in keyboard screen should be enough for the most cases

**Comment by koying** [comment] 2016-03-23 12:26
Ok. I'll mark this one a duplicate of #136

**Closed as completed by koying** 2016-03-23 12:26 UTC
Labels: duplicate
