### ISSUE TITLE
Themoviedb doesn't work anymore

### ISSUE THREAD

**Issue by Mibrechou** [koying/SPMC#1108] opened 2017-11-19 18:35 UTC
Hello

I have tried Today to update my Movie Database and a Message informing about no Connexion is displaying immédiatly.

I have used this function 2 Days ago without Problem.

I have checked with Kodi 17.6 without Problem (except Fanart.... etc...)

Coud you check to verify ?

Regards

JP

**Comment by JonRStorey** [comment] 2017-11-19 21:44
Not working here either

**Comment by ptijoe34** [comment] 2017-11-19 22:04
Hi, I've tested : not working either. 
Everything is ok with universal media scraper, but so slow!!!

**Comment by paulyy88** [comment] 2017-11-20 07:51
Same issue here

**Comment by iatacs19** [comment] 2017-11-20 17:20
I am also having this issue, tested on 2 different Shields on different networks.

**Comment by JonRStorey** [comment] 2017-11-20 19:58
I updated universal media scraper moviedb Add-ons and its working now

**Comment by Mibrechou** [comment] 2017-11-20 20:13
"universal media scraper" :
- is very slow
- no fanart
- no Jacket

**Comment by Biibou** [comment] 2017-11-20 21:41
Check TMDB options, and set the fallback language to english.

**Comment by trotter4** [comment] 2017-11-21 03:18
Also having some trouble with moviedb scraper. Have tried editing the updated addon.xml as suggested earlier in this thread (https://github.com/koying/SPMC/issues/944) with no success. Any suggestions?

**Comment by Skydante** [comment] 2017-11-21 09:02
Hello,

What do you mean by "I updated universal media scraper moviedb Add-ons" JonRStorey ? I use Universal Movie Scraper but it doesn't work anymore if I select the moviedb Add-on, even with the latest version (2.8.9)

**Comment by sns0729** [comment] 2017-11-21 14:58
I'm having the same problem.  The version shown for TMDB scraper is different from the latest that shows in Kodi.   Universal Movie Scraper stopped working as well (latest version).

**Comment by JonRStorey** [comment] 2017-11-21 19:46
I updated to universal scraper 2.8.9 and themoviedb to version 673.9.5 and it started working again

**Comment by dabl2** [comment] 2017-11-21 19:47
Hmm the last update to the Google Play version in July was for the The Movie Database scraper so it looks like it might be time for another fix :)

https://github.com/koying/SPMC/releases
...
16.7.1
@koying koying released this on Jul 30 · 7304 commits to spmc-krypton since this release

FIX: TMDB scrapper
....

EDIT: Per JonRStorey, thought was seeing same, however the 'cannot connect' messages continue when attempting to use The Movie Database as a provider with SPMC 16.7.1 on an Nvidia Shield 2017 16 GB

**Comment by Mibrechou** [comment] 2017-11-21 19:56
I have checked themoviedb version. it's allready version 673.9.5 and not working...

**Comment by ptijoe34** [comment] 2017-11-21 20:30
Same thing for me. I'm on 673.9.5 for the moviedb and Universal media scraper on 2.8.9 and it's not working neither... please fix the problem.

**Comment by Mibrechou** [comment] 2017-11-21 20:34
Note : by going back to Kodi 17.6, the Problem can be solved...

But I will wait some Days : SPMC was better before the Problem occur.

**Comment by ThomMark** [comment] 2017-11-22 08:11
SPMC not working for me either, fully updated and even tested on a fresh install, all to no avail.
Kodi 17.6 is confirmed working, but deffinatily not on SPMC, which I use more.

Please fix 😉

**Comment by ThomMark** [comment] 2017-11-22 16:51
Right, I've been at this all day and I'm 99.9% certain that it can't be fixed manually, I think a new version of SPMC is required to fix the movie database. If I'm wrong, please share.

**Comment by mygoo0205** [comment] 2017-11-22 17:19
Same issue, TMDB not working. TVDB work perfectly on SPMC. 
Regarding Kodi, no issues. 
Please we need a patch to fix SPMC. 
Thanks

**Comment by dabl2** [comment] 2017-11-22 18:01
So can anybody confirm/deny this is/is not a problem with the latest SPMC v17 2017-11-20 build 
in http://download.semperpax.com/spmc/android-arm/ ?

**Comment by ThomMark** [comment] 2017-11-22 18:05
The issue is with 16.7.1 from June 17.
The release you make reference to is a BETA/Test release I believe mate.

**Comment by dabl2** [comment] 2017-11-22 18:08
Yep thanks, was just trying to understand if the problem was limited to the 16.7.1 SPMC release

**Comment by mygoo0205** [comment] 2017-11-22 18:57
For the moment the issue is on 16.7.1 SPMC.

**Comment by ThomMark** [comment] 2017-11-22 19:10
OK guys, here is what I have done so far.
I copied my **com.semperpax.spmc16** to my PC (Backup)
I installed **SPMC-spmc-krypton-2a41374-armeabi-v7a.apk** (Release Date: 2017-11-20 V17.6-alpha1)
Download Here: http://download.semperpax.com/spmc/android-arm/SPMC-spmc-krypton-2a41374-armeabi-v7a.apk
Renamed my com.semperpax.spmc**16** (to) com.semperpax.spmc**17**
Once I launched the new SPMC it migrated my data and everything is working perfect.
I was skeptical about installing a BETA version, but so far I do not notice any difference. 
The scraper program is working perfect again.

I hope this helps some of you, or you could just wait for a patch/update for the 16.7.1 version.

For now, I'm happy! :)

**Comment by ThomMark** [comment] 2017-11-22 19:27
[http://download.semperpax.com/spmc/android-arm/SPMC-spmc-krypton-2a41374-armeabi-v7a.apk](url)

**Comment by permster** [comment] 2017-11-22 20:03
There's an issue with the API key for TMDB.

CCurlFile::Open failed with code 401 for http://api.tmdb.org/3/search/movie?api_key=6889f6089877fd092454d00edb44a84d&query=6%20Days&year=2017&language=en

Which returns an Invalid API key error.

**Comment by ThomMark** [comment] 2017-11-22 20:09
> There's an issue with the API key for TMDB.

CCurlFile::Open failed with code 401 for http://api.tmdb.org/3/search/movie?api_key=6889f6089877fd092454d00edb44a84d&query=6%20Days&year=2017&language=en

Which returns an Invalid API key error.

> So how do you fix that? if possible...  That said, I've upgraded now to BETA and I'm happy with that now.

**Comment by Mibrechou** [comment] 2017-11-22 20:46
Forget SPMC-spmc-krypton-2a41374-armeabi-v7a.apk

WRONG FANART !!!!!!!

Off course with it you can forget kodi....

Therefore : Thank you for Information

**Comment by mygoo0205** [comment] 2017-11-22 21:11
Yes I confirm, wrong Fanart or nous Fanart with SPMC Krypton (tvdb scraper) too bad

**Comment by ThomMark** [comment] 2017-11-22 21:13
> Forget SPMC-spmc-krypton-2a41374-armeabi-v7a.apk

WRONG FANART !!!!!!!

> 

OK, I am confused, I have downloaded some latest movies tonight using this, and all the art work is correct.
Not tried TV series though.

I am sad now, as I felt like the first man on the moon when I upgraded earlier lol

**Comment by mygoo0205** [comment] 2017-11-22 21:14
Yes I confirm, wrong Fanart or no Fanart with SPMC Krypton (tvdb scraper) too bad

**Comment by Mibrechou** [comment] 2017-11-22 21:19
Hi ThomMark 

Don't be confused, you did a goog Job to help us

Regards

**Comment by dabl2** [comment] 2017-11-22 21:27
Not to confuse matters further but when I saw ThomMark's first post I also thought he might be the first man on the moon. 

 In attempting to catch up with the state of this project I just made it through the [Test builds for SPMC 17 (Krypton) #936](https://github.com/koying/SPMC/issues/936) thread.

There were posts in that thread from user thecubasekid many moons ago about upgrading a v16 setup to v17 and follow ups indicating that the v17 installer creates a separate instance on purpose and that if one wants to have their v16 set-up in v17 it is necessary to copy the addons and userdata folders from the  v16 install and replace both folders in the v17 install. Further, for simple setups many addons will likely need to be re-enabled if not downloaded again.

Perhaps the fanart errors with the ThomMark method are related to this?

**Comment by mygoo0205** [comment] 2017-11-22 22:20
For the moment the issue is on 16.7.1 SPMC
We can't access to TMDB scraper. 
Even Latest add-on TMDB updated

**Comment by permster** [comment] 2017-11-22 23:01
Can anyone else confirm the 401 error with the bad TMDB api key in 16.7.1?  That's what I see in the spmc.log on both of my FireTV devices.  The only references I see to the bad api key (6889f6089877fd092454d00edb44a84d) are in the following files in SPMC.

[metadata.common.themoviedb.org/tmdb.xml](https://github.com/koying/SPMC/blob/2a41374753ffb84fa15c234a0e6b5f0f6033a4c4/addons/metadata.common.themoviedb.org/tmdb.xml)
[metadata.themoviedb.org/tmdb.xml](https://github.com/koying/SPMC/blob/2a41374753ffb84fa15c234a0e6b5f0f6033a4c4/addons/metadata.themoviedb.org/tmdb.xml)

**Comment by Mibrechou** [comment] 2017-11-22 23:13
To complete, I have checked acces to : 
"https://api.tmdb.org/3/movie/\1/releases?api_key=6889f6089877fd092454d00edb44a84d&amp"

Result is following message : 
{"status_code":10,"status_message":"Suspended API key: Access to your account has been suspended, contact TMDb."}

**Comment by hwgjjwsr** [comment] 2017-11-23 05:38
Hi. Where can i change the api key in the code? I have an own free account for tmdb. Maybe it works.

Just search and replace in following files?:
metadata.common.themoviedb.org/tmdb.xml
metadata.themoviedb.org/tmdb.xml

Just an idea... I will try today when i'm coming home...

**Comment by hwgjjwsr** [comment] 2017-11-23 05:45
Hmm. But what is the complete path name?
/sdcard/Android/data/om.semperpax.spmc16/.spmc/addons/ ... ?

**Comment by teirfjvn** [comment] 2017-11-23 17:04
In Kodi 16.1 with working tmdb scraper the key is ecbc86c92da237cb9faff6d3ddc4be6d

**Comment by mygoo0205** [comment] 2017-11-23 17:16
The question is how to change the API key ? On Android ?

**Comment by mygoo0205** [comment] 2017-11-23 17:18
And 
what is the complete path name?

**Comment by mygoo0205** [comment] 2017-11-23 19:10
And for SPMC update ? NO news from koying ?

**Comment by NichtDerBert** [comment] 2017-11-24 15:28
here a easy way to change the api key:
- download the 2 zips here: [https://github.com/NichtDerBert/AddonDump/tree/master/zips](https://github.com/NichtDerBert/AddonDump/tree/master/zips)
- and in spmc install from zip

i just edited the api key and added a .1 to the version number so it can be installed, no other changes added

**Comment by networkshokunin** [comment] 2017-11-24 15:57
@NichtDerBert , thank you! Loading the zip files and rebooted just in case. Working well now.

**Comment by mygoo0205** [comment] 2017-11-24 15:59
@NichtDerBert , wonderful thank you !!!!!!!!

**Comment by NichtDerBert** [comment] 2017-11-24 16:17
I just uploaded 2 zips with higher version number, in case there not the same as on my test system.
On my testsystem i had version 4.0.1 and an my other system it was 4.0.2

so, if there are problems on install use the zips with higher version number

**Comment by NichtDerBert** [comment] 2017-11-24 16:31
It looks like, the addon is already fixed in the xbmc repo..
[http://mirrors.kodi.tv/addons/krypton/metadata.themoviedb.org/](http://mirrors.kodi.tv/addons/krypton/metadata.themoviedb.org/)
[http://mirrors.kodi.tv/addons/krypton/metadata.common.themoviedb.org/](http://mirrors.kodi.tv/addons/krypton/metadata.common.themoviedb.org/)

you may want to use th official addon zip from there

**Comment by Mibrechou** [comment] 2017-11-24 18:05
I have tried with the 2 Files without Results...
Not working

Thank you

**Comment by Skydante** [comment] 2017-11-24 18:51
Same for me, it's not working :(

**Comment by mygoo0205** [comment] 2017-11-24 18:52
@NichtDerBert sorry but it's not working , I have try with your 4 files and no result, Smpc can't access to TMDB scraper. So sad :(

**Comment by mygoo0205** [comment] 2017-11-24 19:13
Still waiting an update for SPMC Android...

**Comment by permster** [comment] 2017-11-24 20:13
Debug logs show the following:
`FindMovie: Searching for '6 Days' using The Movie Database scraper (path: '/data/data/com.semperpax.spmc16/cache/apk/assets/addons/metadata.themoviedb.org', content: 'movies', version: '673.9.5')`

It appears to be using the old addon from the apk cache (with bad API key) instead of the currently installed TMDB addon.  I think this solution might work:  https://droidboxforums.com/threads/the-movie-database-scraper-library.10953/

Have to add a 67 in front of the version for each add-on.  So basically what @NichtDerBert did but instead of adding a .1 to the end add a 67 at the beginning of the version.

**Comment by permster** [comment] 2017-11-24 21:11
Modifying the version seems to be working for me after updating the addon.xml for metadata.common.themoviedb.org and metadata.themoviedb.org using the method described in issue #944.

I see @trotter4 mentioned #944 didn't work previously but I'm pretty this will fix the issue for everyone.

**Comment by ptijoe34** [comment] 2017-11-24 21:12
[metadata.themoviedb.org-4.0.2.zip](https://github.com/koying/SPMC/files/1502526/metadata.themoviedb.org-4.0.2.zip)
[metadata.common.themoviedb.org-2.17.4.zip](https://github.com/koying/SPMC/files/1502527/metadata.common.themoviedb.org-2.17.4.zip)

@permster : You're my heros ! 
I went through the indicated forum and  "Shasoosh" uploaded the good modified files. I installed the addons. Everything is good now!


the good files are attached

**Comment by trotter4** [comment] 2017-11-24 21:16
Thank you @permster !

**Comment by mygoo0205** [comment] 2017-11-24 21:44
@permstera big THANKS !

**Comment by Skydante** [comment] 2017-11-24 21:44
It works ! Thanks !

**Comment by Mibrechou** [comment] 2017-11-24 21:46
Hi 

Now, all is working fine

Thank you !!!!!

**Comment by iatacs19** [comment] 2017-11-25 02:30
Adding the "67" to the version for the latest add-on fixed it for me too! Thank you!

**Comment by Prodeje** [comment] 2017-11-25 21:57
How do I fix this on my Nvidia Shield 2017?  I just downloaded SPMC from Play Store.  Not sure how to fix this or edit the 67?  I downloaded ES File Explorer so far and looking around what to edit at this point.

**Comment by iatacs19** [comment] 2017-11-25 22:01
[metadata.themoviedb.org-4.0.3.zip](https://github.com/koying/SPMC/files/1503430/metadata.themoviedb.org-4.0.3.zip)
[metadata.tvdb.com-2.0.6.zip](https://github.com/koying/SPMC/files/1503431/metadata.tvdb.com-2.0.6.zip)

Here you go!

**Comment by Prodeje** [comment] 2017-11-25 22:19
How do I use these zip files on my shield?  Without having to put on a usb drive....  I tried add your thru file manager without luck

**Comment by iatacs19** [comment] 2017-11-25 22:21
You can just copy to the SMB/NFS location where you keep your content, then go to Add-ons and perform an update, choose install from ZIP file then you can browse your network share for the ZIP files you just copied.

**Comment by paulyy88** [comment] 2017-11-25 22:43
Finally, it works! Thank you @iatacs19 much appreciated

**Comment by ThomMark** [comment] 2017-11-26 10:35
Thank you for the hard work, plenty of people involved with trial & error, I have now reverted back to this version and updated.

Working perfect... 👍

**Comment by Prodeje** [comment] 2017-11-26 15:05
I found a usb drive and installed from zip thru SPMC. Worked! Thx!  When will version on tv play store be fixed?

**Comment by 1aranzant** [comment] 2017-11-26 18:30
I do get some data with the newer version of tmdb, but no cast, no art, ...

**Comment by Phanatical** [comment] 2017-11-27 07:19
I'm having the same issue as above. After this manual update, Moviedb somewhat works now but still does not scrape any artwork. Just data. Universal scraper is halfway broken too. It'll only scrape some artwork. Don't know what's going on, all this stuff worked fine a couple weeks ago.

**Comment by Prodeje** [comment] 2017-11-27 13:26
how do we get more attention on this?  This seems to be the highest priority item when looking at the issues log.

**Comment by koying** [comment] 2017-11-27 15:18
Please try one of the 16.7.2 builds from http://download.semperpax.com/spmc/ to confirm it solves the issue

**Comment by manjinanz** [comment] 2017-11-27 18:23
@koying It kinda worked. My new content is showing now but the movie poster looks like a screengrab from the movie rather then the actual movie poster.

Edit: When I go to the movie and select manage, and try to change artwork, no images are available except for the thumbnail which looks the same as mentioned above. Refreshing doesnt fix. And new movies also missing movie ratings.

**Comment by grummel2005** [comment] 2017-11-27 18:37
wherefore the bz2 files are???

**Comment by r2tito** [comment] 2017-11-28 05:07
@koying same as manjinanz, movie data is scraping correctly but the artwork isn't; and trying to change the artwork isn't working either

Edit: updating to 16.7.2 isn't working either

**Comment by Grandmasterseven** [comment] 2017-11-29 08:48
[metadata.themoviedb.org-4.0.2.zip](https://github.com/koying/SPMC/files/1502526/metadata.themoviedb.org-4.0.2.zip)
[metadata.common.themoviedb.org-2.17.4.zip](https://github.com/koying/SPMC/files/1502527/metadata.common.themoviedb.org-2.17.4.zip)

Working with 16.7.2 build.

Thx for All!

**Comment by FMaili** [comment] 2017-11-29 10:28
Hi @all,
how about the Universal Scrapper? I prefer that one as it additionally adds actors and directors. 
Right now both scrapper are good for nothing, even with the 2 zip files installed
Thx in advance!

**Comment by r2tito** [comment] 2017-11-30 06:37
@Grandmasterseven the metadata.common file fixed the posters and fanart; it's still not scraping Disc and Logo art, but is better than nothing, thanks

**Comment by grummel2005** [comment] 2017-11-30 08:16
try this one and check again :)

https://github.com/koying/SPMC/files/1503431/metadata.tvdb.com-2.0.6.zip

**Comment by Dorko** [comment] 2017-11-30 14:45
What version of 16.7.2 build should I use for the Nvidia shield and how can I install it?

**Comment by koying** [comment] 2017-11-30 16:10
New builds with metadata common updated:
http://download.semperpax.com/spmc/

**Comment by 2WhlWzrd** [comment] 2017-11-30 18:38
SPMC-16.7.2-spmc-74d1be1-armeabi-v7a
Working great again.

Thank you.

**Comment by Prodeje** [comment] 2017-11-30 18:44
so does this fully resolve the issue?  Does the android TV play store version (nvidia shield) have this fixed in it?

**Comment by Ulver84** [comment] 2017-12-01 08:55
Which one is the correct one to use on the nvidia shield TV? =)
SPMC-16.7.2-spmc-74d1be1-armeabi-v7a_launcher.apk 
SPMC-16.7.2-spmc-74d1be1-armeabi-v7a.apk

**Comment by Dorko** [comment] 2017-12-01 08:57
I installed SPMC-16.7.2-spmc-74d1be1-armeabi-v7a and TMDB seems to be working again!
Many thanks

What is the launcher.apk? Is this additionally ?

**Comment by koying** [comment] 2017-12-01 14:48
Update Published

**Closed as completed by koying** 2017-12-01 14:48 UTC

**Comment by ThomMark** [comment] 2017-12-03 13:28
Hi Guys

I have just noticed that the same issues exist with the Adult Universe Scraper .
Does anyone happy to have a fix for that one also?

**Comment by LilSnoop40** [comment] 2018-01-05 21:54
can someone advise please, i have tried the SPMC direct from the google play store on my NVIDIA Shield and i get the python error about 2.25 i think.  so i downloaded this version and still happeningSPMC-16.7.2-spmc-74d1be1-aarch64.apk can someone please point me in the right direction?  i read you could edit and xml file but not sure on that one?

Thank you

**Comment by r2tito** [comment] 2018-01-05 23:08
@lilsnoop40 just to let you know... ; I was having the same issue... until I decided to do a new installation; first I cleaned the app cache on android settings; then I cleared the app data and the uninstalled the app completely; rebooted the shield and installed spmc from the play store... then let spmc update all the addons... and it didn't have any python errors; this worked for me 1/3 times

**Comment by LilSnoop40** [comment] 2018-01-06 03:11
ok, i just did something similar than after i had all addons installed that i wanted i was looking to possibly change the skin and i got the error again.  is there a fix for this?  i made a back using ADBLink, then went to restore my fire stick using the backup and it wouldn't gave me the python error.  wonder what i am doing wrong?  thanks

**Comment by r2tito** [comment] 2018-01-08 00:19
@LilSnoop40 i understand what you're saying, and i had that same problem too, installing the titan Skin after a fresh install; even on one time the skin was not appearing on the kodi repo; i don't know exactly why or how did it fixed; i just redo the entire install again and again until it finally fixed itself; my only guess is that when it's unpacking the apk and installing something goes wrong sometimes, but like i said, i don't know how or why

**Comment by Skydante** [comment] 2018-01-21 11:51
The problem is back :(

**Comment by tankalf** [comment] 2018-01-21 19:47
Still here, scraper doesn't work anymore... Nvidia Shield user

**Comment by Fotospecht** [comment] 2018-01-24 14:08
Themoviedb isn't working since a few days.
Please reopen this issue or create a new one.

**Comment by jamuir** [comment] 2018-03-04 22:27
I just installed kodi on ubuntu by following the instructions here:

https://kodi.wiki/view/HOW-TO:Install_Kodi_for_Linux

I hit this issue (i.e. TheMovieDB server would not respond).

However, I just updated the TheMovieDB add-on from inside Kodi, and now it is working.

**Comment by m0Chandras** [comment] 2018-03-17 23:32
Scraper still broken
