### ISSUE TITLE
"Square blocks" font issue

### ISSUE THREAD

**Issue by grummel2005** [koying/SPMC#99] opened 2016-03-17 14:18 UTC
when i installed 16.1.1 i have font problems so letters are shown as small bricks

how can i solve this problem?

when i go to settings (i know where to go because of parallel use of another device :) ) then some menues are in right font

**Comment by grummel2005** [comment] 2016-03-17 14:34
see screenshot

![screenshot_2016-03-17-15-01-21](https://cloud.githubusercontent.com/assets/17906557/13849277/bc3b2406-ec55-11e5-9e47-d8ab64784f54.png)

**Comment by koying** [comment] 2016-03-17 14:40
Could you check if enabling "Arial-based" fonts in the Skin settings changes anything?

**Comment by grummel2005** [comment] 2016-03-17 14:42
i checked this already before problem posted here - no changes

**Comment by grummel2005** [comment] 2016-03-18 07:39
i played a little with settings but did not found a solution
in 15.0.0 everything is okai :)

**Comment by grummel2005** [comment] 2016-03-18 10:42
when i am playing around the menues the according right letters will come up but after new start the old situation is there.
i deleted the cache of the app via android but no changes
help would be appreciated :)

**Comment by cesarious** [comment] 2016-03-19 12:21
This happened to me with the first versions of passthrough tests. It seems to be related to Confluence skin. You may temporarily fix it by changing the font through system/appearance/skin font.

I recall that sometimes was also fixed by Shield rebooting, but randomly the issue returned.

To be honest, it fixed itself with use time (perhaps a background update that I do not recall and/or uninstall and install new beta versions).

I'm still on Lollipop with the Shield, can not comment on updated Shield.

Hopefully this helps a bit.

**Comment by grummel2005** [comment] 2016-03-19 15:12
i cannot agree to you - i am using SPMC for some days very intensive and nothing repairs it by it self.
sometimes during use it is after some menues okai but if i start the app new it is the same problem
as i said i tried all font settings - nothing helps
i changed to another skin - there no problems - when i go back to normal skin - problems

**Comment by grummel2005** [comment] 2016-03-21 12:34
no changes with new version :(

**Comment by koying** [comment] 2016-04-02 09:21
I cannot reproduce, but I've seen other reports of this.
Debug log might help

**Comment by war59312** [comment] 2016-04-02 13:52
This only happens to me if I turn on 4K 23.976Hz:

Settings > HDMI > Resolution > "4K 23.976Hz"

**Comment by grummel2005** [comment] 2016-04-02 14:49
in log is nothing to this point
i think because spmc think everything is okai :(

**Comment by koying** [comment] 2016-04-02 15:05
And how would you know what I'm looking for in the log?

**Comment by grummel2005** [comment] 2016-04-02 17:04
which log would you like to have then? :)
and how i send it to you?

**Comment by war59312** [comment] 2016-04-03 04:34
See: http://kodi.wiki/view/Log_file/Advanced#Enable_debugging

**Comment by grummel2005** [comment] 2016-04-05 11:03
in new version still the problem:
- which logs do you need?
- where to send to?

thx a lot!
i know how to set them on but there are some special things i have to set on special - so i do not know what you need and where to send to

**Comment by koying** [comment] 2016-04-05 18:14
Please try http://download.semperpax.com/spmc/android-arm/SPMC-20160404-6a4e984-spmc-jarvis-armeabi-v7a.apk

**Comment by grummel2005** [comment] 2016-04-06 03:58
thx but when i install it i cannot update via google play anymore
this is right?

**Comment by grummel2005** [comment] 2016-04-07 11:47
i had been to curious :)
installed
BINGO - problem solved
thx a lot!!!

**Comment by grummel2005** [comment] 2016-04-08 04:10
what was the problem and the solution?

**Closed as completed** 2016-04-23 10:27 UTC
Labels: bug
