### ISSUE TITLE
RK3288

### ISSUE THREAD

**Issue by blondin76** [koying/SPMC#126] opened 2016-03-21 11:15 UTC
he Koying,

I'm french sorry for my english

I poseur of a chameleon with a RK3288 chipset cloudmedia
is it expected an evolution of Kodi in SMPC 16 with the support of the RK3288?

thank you in advance for your response

**Comment by koying** [comment] 2016-03-21 11:17
Duplicate of #68

**Closed as completed by koying** 2016-03-21 11:17 UTC
Labels: duplicate
