### ISSUE TITLE
Media Flags/ Thumbail Issue (MySQL)

### ISSUE THREAD

**Issue by uhnonuhmuhs** [koying/SPMC#207] opened 2016-04-11 15:14 UTC
Hello. When using the latest SPMC on an Nvidia Shield, I am having an issue with it either not receiving or displaying media flag info when connected to a MySQL database (displays SD flag when file is HD, no codec info, etc). Anyway, once the file is played, the correct media flags are displayed. This occurs on both Confluence and Arctic Zephyr so I do not believe it to be a skin-related issue. Library is shared via NFS. 

I've tried doing a clean install a number of times to no avail (both client and MySQL server). Official Kodi installed alongside SPMC on Nvidia Shield does not have this issue. Also have a Wetek Core running official Kodi connected to MySQL DB that is working as expected.

Have also noticed that at times thumbnails are also not displayed. Again, this is not an issue with any other install on the network including offical Kodi installed alongside SPMC on Nvidia Shield.

I'm not 100% certain this behavior is limited to using a MySQL DB. This troubleshooting process has been a bit exhausting so I do not recall whether I tested with a local DB or not. Please let me know if I can provide you any further info. 

BTW, thanks for SPMC. I really do prefer it to Kodi on Android and hope you're able to continue delivering this awesome fork.

**Comment by heymoe** [comment] 2016-04-13 13:06
I've been using a MySQL DB with Kodi and now SPMC for a long time.

When I switched to SPMC on my Shield TV, I copied my Kodi data directory / configuration over to SPMC.

I have since added new content to my Kodi/SPMC video library and the meta data displayed about the new content in SPMC lines up with what the content is. As in, correct HD or SD labels, video resolution (e.g.: 1080p, 720p, etc..), Audio format (e.g: AC3, TrueHD, DTS, DTS-HD, etc..). aspect ratio, etc.. . Also fan art and thumbnails seem to show up correctly for me too. 

I running the Aeon MQ6 skin but I don't think a skin would make a difference when it comes to the meta data for content in the library.

**Comment by koying** [comment] 2016-04-13 14:41
Duplicate of #176 ?

**Comment by uhnonuhmuhs** [comment] 2016-04-13 22:11
Very possible that it's a duplicate. I want to add that sometimes I also get doubled entries that warn that the video is no longer available when I try to play either of them until I do a manual library update. Video plays fine after that. Also, when the thumbnail is missing, playing the file usually resolves that (thumbnail is there when video is stopped).

**Comment by koying** [comment] 2016-04-24 14:01
Fixed

**Closed as completed by koying** 2016-04-24 14:01 UTC
Labels: duplicate
