### ISSUE TITLE
Subtitle offset small display bug

### ISSUE THREAD

**Issue by tar-gezed** [koying/SPMC#157] opened 2016-03-28 13:03 UTC
Hi :)
Since Kodi 16.0, the subtitle offset dialog (see picture below) has a small display bug. When I try to delay subs, I can't see of how many seconds I delayed it. I haven't any problem on Kodi 15 and it's not theme related because even with Confluence I have the same problem.
Maybe it's language related (my SPMC UI is in french)
Look at this screenshot : http://www.hostingpics.net/viewer.php?id=880642IMG20160328145036.jpg
The "normal" display is "Avance XX.XXX seconds" but as you can see now I only see "Avanc" and the end of the string is cut, too much shift on the right to display the complete string.
Hope that you can fix this :)
Thanks in advance and thanks for your hard work :)

**Comment by koying** [comment] 2016-04-02 08:22
duplicate of #168

**Closed as completed by koying** 2016-04-02 08:22 UTC
Labels: duplicate
