### ISSUE TITLE
no sound on  but fine on kodi

### ISSUE THREAD

**Issue by Tottenha7819** [koying/SPMC#115] opened 2016-03-19 16:39 UTC
Hi I want to migrate to spmc from but I am able to with this issue. I was watching sister wives using a third party add-on but the  link  I was using works fine  but no sound. In kodi the same link work fine with sound. Here are my logs.
http://spmclogs.semperpax.com/pwqexpgap

http://spmclogs.semperpax.com/per2veq3p 
I have included both new and old logs.

**Comment by koying** [comment] 2016-03-20 12:01
Duplicate of #90

**Closed as completed by koying** 2016-03-20 12:01 UTC
Labels: duplicate
